In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 670.6 kB/s eta 0:00:19
   - -------------------------------------- 0.5/12.6 MB 670.6 kB/s eta 0:00:19
   -- ------------------------------------- 0.8/12.6 MB 759.0 kB/s eta 0:00:16
   --- ------------------------------------ 1.0/12.6 MB 765.4 kB/s eta 0:00:16
   --- ------------------------------------ 1.0/12.6 MB 765.4 kB/s eta 0:00:16
   --- ------------------------------------ 1.0/12.6 MB 765.4 kB/s eta 0:00:16
   --- ------------------------------------ 1.0/12.6 MB 765.4 kB/s eta 0:00:16
   ---- ----------------------------------- 1.3/12.6 MB 549.6 kB/s eta 0:00:21
   ---- ----------------------------------- 1.3/12.6 MB 549.6 kB/s eta 0:00:21
   ---- -

In [8]:

import numpy as np 
words = np.array(["nombre", "pronombre", "verbo", "adverbio", "adjetivo", "conjunción", "Preposición"])

In [9]:
words[0] #En python la posicion del vector empieza desde 0 en adelante.

np.str_('nombre')

In [ ]:
words[0:7] # selecciona los elementos del índice 0 hasta el 6, En Python, cuando dices [inicio:fin], el fin no se incluye.

array(['nombre', 'pronombre', 'verbo', 'adverbio', 'adjetivo',
       'conjunción', 'Preposición'], dtype='<U11')

In [10]:
words[0:] #Significa "selecciona desde el índice 0 hasta el final".

array(['nombre', 'pronombre', 'verbo', 'adverbio', 'adjetivo',
       'conjunción', 'Preposición'], dtype='<U11')

In [11]:
#En Python, cuando haces slicing (inicio:fin:paso):
#inicio ➔ desde dónde empezar (vacío = desde el final).
#fin ➔ hasta dónde llegar (vacío = hasta el principio).
#paso ➔ cuánto te mueves. Aquí es -1, paso negativo, así que invierte el array

words[::-1]


array(['Preposición', 'conjunción', 'adjetivo', 'adverbio', 'verbo',
       'pronombre', 'nombre'], dtype='<U11')

In [44]:
numbers = np.array([1,3,5.3])
numbers

array([1. , 3. , 5.3])

In [47]:
numbers [::-1]

array([5.3, 3. , 1. ])

In [49]:
numbers.sum()

np.float64(9.3)

In [52]:
numbers.size #Tamaño del vector 

3

In [ ]:
numbers.mean() #Promedio del vector

np.float64(3.1)

In [ ]:
np.count_nonzero(numbers) #Cuneta cuántos elementos del array no son cero.

3

In [71]:
np.round(numbers) #Redondea al numero entero más cercano 

array([1., 3., 5.])

In [ ]:
numbers[2] = np.round(numbers[2]) #Redondea un numero especifico del vector y lo guarda
numbers

array([1., 3., 5.])

In [99]:
numbers.sort() #Ordena el vector de forma ascendente
numbers

array([1., 3., 5.])